language: go
go:
- 1.5
env:
  global:
  - PATH=~/gopath/bin:$PATH
  - DEBIAN_FRONTEND=noninteractive
  - secure: "eVK4VPUaQNF1a3CMUz/5jWaNY0+Wj10HnscPhcvmnH+IUJ+B6n2W4M5ht5WXEmx5EnKgLIZveL9CtPJTTsW4lE1RO03xfuVoe8+dElUSlKLJEHIDKm7koYgFEURWZXRcMAMqW2yj3y7D34fnwP4Evt/HuV8ZtWktMtJUzLr12oFxQDS0RC7II5nh8BiqSGCkKC8QJ6qQzbjZavBQ8M70Y4WWPArYHzwcSQjOLxhQmGCyx9JI7/nIqSosldFwqiFTh+UH3x7Pntt1Ji6Ra0rAuGFN28nQc8ISxfytwAgV4h7ubAWPUom2rXdUpHVvWZXoxDJr8YYq4rGRmyuLl/gBUfv72l/u8wIlMo5gRB2vJXHwKAaogSheGtdVwv7BwPSvjA6oOz5imqkhIm5kNgyrXaBglF7fornPiJNVgv2lMzuLB3GgqjYxhfipFahJT99x91/xd6kZ5OSSUVYkTx/0JwkEmGXyOJNzynC22VNHj6u1T41hkRHHSUjzrNBwNhMEcXDy75VaJukKMi9YyyHgehitWUFnGq0rakMz3tQxeO8K6YVQqjD7NWPiHh1vh4vWYRn2/T7ewTksW1h+/ETJR98YYsjpHnuQSJh6gGj6i4jKKy04hWagVciJ3Jr4i6ouA8ggKoEMzEB9KXd44yJoXk/ozk5VOXPithyp8NuA5BA="
sudo: false
addons:
  apt:
    packages:
      - rpm
      - devscripts
      - debhelper
install:
- go get github.com/mitchellh/gox
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make lint
- make cover
- make all
after_script:
- goveralls -coverprofile=.profile.cov
before_deploy:
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=100 || true
- git fetch --tags --depth=100 || true
deploy:
- provider: script
  script: tool/releng --task=upload-to-github-release -v
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: tool/releng --task=create-pullrequest --current-branch=$TRAVIS_BRANCH --spec-files=packaging/rpm/mackerel-check-plugins.spec -v
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
